"""upgrading

Revision ID: 16288f55f399
Revises: 1fbfa43fdc29
Create Date: 2024-01-11 22:43:51.114124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16288f55f399'
down_revision = '1fbfa43fdc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
